name = "tus-conformance-tests"
engineVersion = "v1.0.0"
runtime.source = "dang"
include = ["!.devenv", "!results"]

[[dependencies]]
name = "hurl"
source = "github.com/sagikazarmark/daggerverse-beta/hurl"
